### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by davej** [firejune/electron-react-devtools#1]
It seems to install ok from the console but the React tab does not appear in my devtools

<img width="689" alt="screen shot 2016-05-25 at 18 51 12" src="https://cloud.githubusercontent.com/assets/26971/15550535/bc6103a8-22a9-11e6-8c10-69bce8ef321b.png">

Using Electron 1.0.2 and React 15.0.1. Also using Webpack and Babel in my build if that makes a difference.

**Comment by philostler** [comment]
Same experience as @davej using Electron 1.1.1 and React 15.1.0

**Comment by firejune** [comment]
It's not working `content_scripts` in `manifest.json` on Electron. So React's inject script loading menualy.
I add a API for script injecting new version 0.1.5. please update this module.

Then add the React's inject script in to `main.html`(or entry root js) before loading your app
source running on renderer process:
```html
...
<script>
  // in development.
  require('electron-react-devtools').inject()
 // your app root running on renderer process.
  require('./src')
</script>
...
```

Thanks for your feedback.

**Comment by davej** [comment]
Thanks, was able to get it working in one step using:

```html
<script>
  if (process.env.NODE_ENV !== 'production') {
    const electronReactDevTools = require('electron-react-devtools');
    electronReactDevTools.inject();
    electronReactDevTools.install();
  }
  …
</script>
```

Might be a bit easier to present the install instructions in one step like this rather than asking the user to write `require('electron-react-devtools').install()` in their console.

Thanks for all your great work :-)

**Comment by enlight** [comment]
> Might be a bit easier to present the install instructions in one step like this rather than asking the user to write require('electron-react-devtools').install() in their console.

`require('electron-react-devtools').install()` only needs to be executed once, after that the DevTools extension will be loaded automatically every time you run your Electron app.

**Comment by davej** [comment]
> require('electron-react-devtools').install() only needs to be executed once

That doesn't seem to be the case for me. Other devtools plugins like spectron work like this but electron-react-devtools seems to require to be installed on every run for every window.
