### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by 3rdey3** [firejune/electron-react-devtools#5]
electron-react-devtools dosn't work with React 16. Following error is thrown in console -

> warning.js:33 Warning: The installed version of React DevTools is too old and will not work with the current version of React. Please update React DevTools. https://fb.me/react-devtools

**Comment by hendrikswan** [comment]
Hi! Got the same issue. I am happy to do a PR, but I'm not sure how to do it. It seems like this project has files copied over from `react-devtools`?

**Comment by sheldhur** [comment]
You can force download chrome extencion in `electron-devtools-installer`. 
[https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/index.js#L17](url)

**Comment by hendrikswan** [comment]
@sheldhur I'm not quite sure what you mean..

**Comment by craigcosmo** [comment]
any update guys?

**Comment by firejune** [comment]
Job done. Thanks!

**Comment by hendrikswan** [comment]
Thanks @firejune! Just installed it and can confirm it's working again.

**Comment by craigcosmo** [comment]
confirm, new version works
